# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare:
    runs-on: ubuntu-latest

  approve1:
    runs-on: ubuntu-latest
    needs: prepare
    environment: "0001"

  approve2:
    runs-on: ubuntu-latest
    needs: prepare
    environment: "0002"

  wait-approval:
    runs-on: ubuntu-latest
    needs: [approve1, approve2]

    steps:
    - name: echo
      run: echo "Approved."

  greet:
    if: ${{ false }} # disable for now
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: DEV
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Compare Secret with String
      run: |
        if [ "$TEST_SECRET" = "TESTDEV" ]; then
          echo "The secret matches the string. $TEST_SECRET"
        else
          echo "The secret does not match the string. $TEST_SECRET"
        fi
        echo "The secret length: ${#TEST_SECRET}"
      env:
        TEST_SECRET: ${{ secrets.TEST }}
